-- MySQL Script generated by MySQL Workbench
-- Wed Sep 18 18:43:56 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Hotel management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Hotel management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Hotel management` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Hotel management` ;

-- -----------------------------------------------------
-- Table `Hotel management`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel management`.`Customers` ;

CREATE TABLE IF NOT EXISTS `Hotel management`.`Customers` (
  `idCustomers` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `phone_number` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `booking_history` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCustomers`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Hotel management`.`Room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel management`.`Room` ;

CREATE TABLE IF NOT EXISTS `Hotel management`.`Room` (
  `Room_id` INT NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `price_per_night` VARCHAR(45) NOT NULL,
  `special_amenities` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Room_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Hotel management`.`Room_reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel management`.`Room_reservations` ;

CREATE TABLE IF NOT EXISTS `Hotel management`.`Room_reservations` (
  `reservation_id` INT NOT NULL,
  `arrival_date` DATETIME NOT NULL,
  `departure_date` DATETIME NOT NULL,
  `number_of_guests` INT NOT NULL,
  `special_preferences` VARCHAR(45) NOT NULL,
  `reservation_status` VARCHAR(45) NOT NULL,
  `Customers_idCustomers` INT NOT NULL,
  `Room_Room_id` INT NOT NULL,
  PRIMARY KEY (`reservation_id`, `Customers_idCustomers`, `Room_Room_id`),
  INDEX `fk_Room_reservations_Customers_idx` (`Customers_idCustomers` ASC) VISIBLE,
  INDEX `fk_Room_reservations_Room1_idx` (`Room_Room_id` ASC) VISIBLE,
  CONSTRAINT `fk_Room_reservations_Customers`
    FOREIGN KEY (`Customers_idCustomers`)
    REFERENCES `Hotel management`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Room_reservations_Room1`
    FOREIGN KEY (`Room_Room_id`)
    REFERENCES `Hotel management`.`Room` (`Room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Hotel management`.`Billing and payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel management`.`Billing and payment` ;

CREATE TABLE IF NOT EXISTS `Hotel management`.`Billing and payment` (
  `idBilling and payment` INT NOT NULL AUTO_INCREMENT,
  `Room_cost` VARCHAR(44) NOT NULL,
  `additional_services_used` VARCHAR(45) NOT NULL,
  `tax` VARCHAR(45) NOT NULL,
  `other_charges` VARCHAR(45) NOT NULL,
  `payment_method` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `Room_reservations_reservation_id` INT NOT NULL,
  `Room_reservations_Customers_idCustomers` INT NOT NULL,
  `Room_reservations_Room_Room_id` INT NOT NULL,
  PRIMARY KEY (`idBilling and payment`, `Room_reservations_reservation_id`, `Room_reservations_Customers_idCustomers`, `Room_reservations_Room_Room_id`),
  INDEX `fk_Billing and payment_Room_reservations1_idx` (`Room_reservations_reservation_id` ASC, `Room_reservations_Customers_idCustomers` ASC, `Room_reservations_Room_Room_id` ASC) VISIBLE,
  CONSTRAINT `fk_Billing and payment_Room_reservations1`
    FOREIGN KEY (`Room_reservations_reservation_id` , `Room_reservations_Customers_idCustomers` , `Room_reservations_Room_Room_id`)
    REFERENCES `Hotel management`.`Room_reservations` (`reservation_id` , `Customers_idCustomers` , `Room_Room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Hotel management`.`Hotel_services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel management`.`Hotel_services` ;

CREATE TABLE IF NOT EXISTS `Hotel management`.`Hotel_services` (
  `idHotel` INT NOT NULL AUTO_INCREMENT,
  `services` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `opening_hrs` VARCHAR(45) NOT NULL,
  `Customers_idCustomers` INT NOT NULL,
  PRIMARY KEY (`idHotel`, `Customers_idCustomers`),
  INDEX `fk_Hotel_services_Customers1_idx` (`Customers_idCustomers` ASC) VISIBLE,
  CONSTRAINT `fk_Hotel_services_Customers1`
    FOREIGN KEY (`Customers_idCustomers`)
    REFERENCES `Hotel management`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Hotel management`.`customer_feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel management`.`customer_feedback` ;

CREATE TABLE IF NOT EXISTS `Hotel management`.`customer_feedback` (
  `feedback_id` INT NOT NULL AUTO_INCREMENT,
  `rating` VARCHAR(45) NOT NULL,
  `comments` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `Customers_idCustomers` INT NOT NULL,
  `Room_reservations_reservation_id` INT NOT NULL,
  `Room_reservations_Customers_idCustomers` INT NOT NULL,
  `Room_reservations_Room_Room_id` INT NOT NULL,
  PRIMARY KEY (`feedback_id`),
  INDEX `fk_customer_feedback_Customers1_idx` (`Customers_idCustomers` ASC) VISIBLE,
  INDEX `fk_customer_feedback_Room_reservations1_idx` (`Room_reservations_reservation_id` ASC, `Room_reservations_Customers_idCustomers` ASC, `Room_reservations_Room_Room_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_feedback_Customers1`
    FOREIGN KEY (`Customers_idCustomers`)
    REFERENCES `Hotel management`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_feedback_Room_reservations1`
    FOREIGN KEY (`Room_reservations_reservation_id` , `Room_reservations_Customers_idCustomers` , `Room_reservations_Room_Room_id`)
    REFERENCES `Hotel management`.`Room_reservations` (`reservation_id` , `Customers_idCustomers` , `Room_Room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Hotel management`.`Room_reservations_has_Hotel_services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel management`.`Room_reservations_has_Hotel_services` ;

CREATE TABLE IF NOT EXISTS `Hotel management`.`Room_reservations_has_Hotel_services` (
  `Room_reservations_reservation_id` INT NOT NULL,
  `Room_reservations_Customers_idCustomers` INT NOT NULL,
  `Hotel_services_idHotel` INT NOT NULL,
  PRIMARY KEY (`Room_reservations_reservation_id`, `Room_reservations_Customers_idCustomers`, `Hotel_services_idHotel`),
  INDEX `fk_Room_reservations_has_Hotel_services_Hotel_services1_idx` (`Hotel_services_idHotel` ASC) VISIBLE,
  INDEX `fk_Room_reservations_has_Hotel_services_Room_reservations1_idx` (`Room_reservations_reservation_id` ASC, `Room_reservations_Customers_idCustomers` ASC) VISIBLE,
  CONSTRAINT `fk_Room_reservations_has_Hotel_services_Room_reservations1`
    FOREIGN KEY (`Room_reservations_reservation_id` , `Room_reservations_Customers_idCustomers`)
    REFERENCES `Hotel management`.`Room_reservations` (`reservation_id` , `Customers_idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Room_reservations_has_Hotel_services_Hotel_services1`
    FOREIGN KEY (`Hotel_services_idHotel`)
    REFERENCES `Hotel management`.`Hotel_services` (`idHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Hotel management`.`Hotel_services_has_Room_reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel management`.`Hotel_services_has_Room_reservations` ;

CREATE TABLE IF NOT EXISTS `Hotel management`.`Hotel_services_has_Room_reservations` (
  `Hotel_services_idHotel` INT NOT NULL,
  `Hotel_services_Customers_idCustomers` INT NOT NULL,
  `Room_reservations_reservation_id` INT NOT NULL,
  `Room_reservations_Customers_idCustomers` INT NOT NULL,
  `Room_reservations_Room_Room_id` INT NOT NULL,
  PRIMARY KEY (`Hotel_services_idHotel`, `Hotel_services_Customers_idCustomers`, `Room_reservations_reservation_id`, `Room_reservations_Customers_idCustomers`, `Room_reservations_Room_Room_id`),
  INDEX `fk_Hotel_services_has_Room_reservations_Room_reservations1_idx` (`Room_reservations_reservation_id` ASC, `Room_reservations_Customers_idCustomers` ASC, `Room_reservations_Room_Room_id` ASC) VISIBLE,
  INDEX `fk_Hotel_services_has_Room_reservations_Hotel_services1_idx` (`Hotel_services_idHotel` ASC, `Hotel_services_Customers_idCustomers` ASC) VISIBLE,
  CONSTRAINT `fk_Hotel_services_has_Room_reservations_Hotel_services1`
    FOREIGN KEY (`Hotel_services_idHotel` , `Hotel_services_Customers_idCustomers`)
    REFERENCES `Hotel management`.`Hotel_services` (`idHotel` , `Customers_idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hotel_services_has_Room_reservations_Room_reservations1`
    FOREIGN KEY (`Room_reservations_reservation_id` , `Room_reservations_Customers_idCustomers` , `Room_reservations_Room_Room_id`)
    REFERENCES `Hotel management`.`Room_reservations` (`reservation_id` , `Customers_idCustomers` , `Room_Room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
